services:
  dind:
    image: docker:dind
    container_name: dind-container
    privileged: true
    environment:
      - DOCKER_TLS_CERTDIR=""
    networks:
      - kind-network
    ports:
      - "2375:2375"  # Exponemos el puerto 2375 para que otros contenedores lo utilicen

  kind:
    image: alpine
    container_name: kind-container
    environment:
      - DOCKER_HOST=tcp://dind-container:2375  # Conectamos Kind al Docker del contenedor DIND
    networks:
      - kind-network
    command:
      - tail
      - -f
      - /dev/null
    depends_on:
      - dind
    stdin_open: true
    tty: true

networks:
  kind-network:
    driver: bridge

