name: Kubernetes
on:
  push:
    branches:
      - main
  workflow_dispatch:
   

jobs:
  dagger:
    runs-on: ubuntu-latest

    steps:
    
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Kubernetes exec
        uses: dagger/dagger-for-github@v6
        with:
          workdir: kubernetes
          verb: call
          args: --docker-socket=/var/run/docker.sock --kind-svc=tcp://127.0.0.1:3000 container with-exec --args kubectl --args get --args nodes sync
          version: "0.14.0"
